import socket
import threading
import time
import os

import requests as http_requests
from scapy.all import sniff, wrpcap, IP
 
CAPTURE_DIR     = "captures"
CAPTURE_TIMEOUT = 10
PCAP_FILENAME   = "capture.pcap"
PCAP_A          = "capture_a.pcap"
PCAP_B          = "capture_b.pcap"
 
os.makedirs(CAPTURE_DIR, exist_ok=True)
 
     #capture packets
def capture_traffic(url: str, pcap_name: str = PCAP_FILENAME) -> str:
    """
    Capture network packets generated by visiting *url*.
    Returns the full path to the saved .pcap file.
    """
    hostname  = _extract_hostname(url)
    target_ip = _resolve_ip(hostname)
    pcap_path = os.path.join(CAPTURE_DIR, pcap_name)
 
    captured_packets = []
    stop_event       = threading.Event()
 
    def _packet_handler(pkt):
        if IP in pkt:
            if pkt[IP].src == target_ip or pkt[IP].dst == target_ip:
                captured_packets.append(pkt)
 
    def _sniffer():
        sniff(
            prn=_packet_handler,
            store=False,
            timeout=CAPTURE_TIMEOUT,
            stop_filter=lambda _: stop_event.is_set(),
        )
 
    sniffer_thread = threading.Thread(target=_sniffer, daemon=True)
    sniffer_thread.start()
 
    time.sleep(0.3)
    _send_request(url)
 
    sniffer_thread.join(timeout=CAPTURE_TIMEOUT + 2)
    stop_event.set()
 
    if captured_packets:
        wrpcap(pcap_path, captured_packets)
    else:
        wrpcap(pcap_path, [])
 
    return pcap_path
 
 
def _extract_hostname(url: str) -> str:
    return url.replace("https://", "").replace("http://", "").split("/")[0]
 
 
def _resolve_ip(hostname: str) -> str:
    try:
        return socket.gethostbyname(hostname)
    except socket.gaierror:
        return ""
 
 
def _send_request(url: str) -> None:
    try:
        http_requests.get(
            url,
            timeout=8,
            headers={"User-Agent": "SnoopyNetSniffer/1.0"},
            allow_redirects=True,
        )
    except Exception:
        pass
 